Create NobleController.java and fix TurnController.java
Splendor-Mobile-Game/ClientSide pull request #120
Opened 2023-05-12 16:29 UTC by EaZZyHK

I've created NobleController. I am unsure if it's appropriately made, so please check it thoroughly.

2023-05-12 20:56 UTC, kestivvi requested changes
Great addition!

Please, initialize NobleController in the GameActivity and assign to it appropriate message type that it should receive.

2023-05-12 20:56 UTC, kestivvi commented on app/src/main/java/com/example/splendormobilegame/activities/GameActivity/NobleController.java
> +    public class NobleReceivedMessageHandeler extends UserReaction {
Typo

2023-05-13 08:50 UTC, EaZZyHK commented
I believe, that this new commit is what you have asked for

2023-05-13 09:30 UTC, kestivvi requested changes

2023-05-13 09:30 UTC, kestivvi commented on app/src/main/java/com/example/splendormobilegame/activities/GameActivity/GameActivity.java
> +        );
Instance of `nobleController` is not created in the `onCreate` method, but it should like others controllers.

2023-05-13 09:47 UTC, kestivvi approved these changes
Awesome 🎉🎉🥳

2023-05-13 09:47 UTC, merged