createWebSocketClient getting server id form properites file
Splendor-Mobile-Game/ClientSide pull request #20
Opened 2023-03-29 21:49 UTC by Antonidass5

I created a properites file and changed createWebSocketClient to get server id form properites file.

2023-03-29 21:57 UTC, kestivvi requested changes
I do not allow properties file to be in the `src` directory. It can be in`app` directory, it can be in the to level directory of this repo. But not in the `src`, the should be only the code. (*src* stands for *source code*)

2023-04-01 07:09 UTC, Vertonowsky commented
Test the functions before merging. Current code is not properly loading the property value from file.

2023-04-03 15:46 UTC, Vertonowsky submitted a review, later dismissed

2023-04-03 20:03 UTC, kestivvi requested changes

2023-04-03 20:03 UTC, kestivvi commented on app/src/main/java/com/example/splendormobilegame/config/Config.java
> +            InputStream inputStream = context.getAssets().open("conig.properties");
I've run app at this commit. And it didn't work. I suppose this line causes errors.

2023-04-03 20:08 UTC, kestivvi commented
Please, also do the followings:
- format your code (there are for example places where there is too much blank lines)
- add java docs to the relevant parts

2023-04-03 20:11 UTC, kestivvi commented
At the end please also resolve merge conflicts so it can actually be merged to the develop.

2023-04-05 18:22 UTC, Vertonowsky submitted a review, later dismissed

2023-04-12 21:51 UTC, KamilDevelopments requested changes
You've deleted half of the repository, probadly when you were merging files you accepted your version instead of actually merging it.

2023-04-13 10:10 UTC, kestivvi commented
I fixed it by undoing the last commit, then resolving the merge conflicts properly, and finally pushing it with git --force.

2023-04-13 10:10 UTC, kestivvi approved these changes

2023-04-13 13:14 UTC, KamilDevelopments approved these changes

2023-04-13 16:12 UTC, merged