Make rooms work online
Splendor-Mobile-Game/ClientSide pull request #42
Opened 2023-04-08 21:24 UTC by kestivvi

Now rooms work online with communication via server.

You can now create a room, join the existing one and leave the room you are currently in. I added some text views in the waiting room for debugging purposes. Those will be deleted and the activity will be properly stylized by our UI/UX team.

Of course, while implementing this stuff, I realized that there are a lot of thing badly written by me on the server side. So there is related PR on the server side that has to be merged simultaneously.

2023-04-08 21:32 UTC, kestivvi commented
If you want to test this particular pull request branch and also use the related branch on the server you have to change the line in the gradle file from
```
implementation 'com.github.Splendor-Mobile-Game:ServerSide:develop-SNAPSHOT'
```
to
```
implementation 'com.github.Splendor-Mobile-Game:ServerSide:allow-client-to-use-rooms-SNAPSHOT'
```

2023-04-09 07:07 UTC, Vertonowsky requested changes

2023-04-09 07:07 UTC, Vertonowsky commented on app/src/main/java/com/example/splendormobilegame/model/Room.java
> +            .orElse(null);
😒🤓

2023-04-09 07:07 UTC, Vertonowsky commented on app/src/main/java/com/example/splendormobilegame/JoinRoomActivity.java
> +                String enterCode = binding.enterNameEditText.getText().toString();
change the `enterNameEditText` name. Since we don't require the room's name

2023-04-09 07:07 UTC, Vertonowsky commented on app/src/main/java/com/example/splendormobilegame/websocket/reactions/CreateRoomResponse.java
> +        Utils.showToast("Cannot create room, your fault: " + errorResponse.data.error);
Dont say who's fault it was. Just display the error

2023-04-09 09:33 UTC, KamilDevelopments commented
Game does't recognise someone leaving the room. I created room on one device, closed an app and than opened it again and couldn't do anything becouse game still tought im in waiting room. We need to implement removing player from the room when he presses go back button or just closes an app.

2023-04-09 10:06 UTC, kestivvi commented
> Game does't recognise someone leaving the room. I created room on one device, closed an app and than opened it again and couldn't do anything becouse game still tought im in waiting room. We need to implement removing player from the room when he presses go back button or just closes an app.

That's right. It wasn't my intent to implement handling that case. Do we want do this in this PR or in the another one?

2023-04-09 10:24 UTC, KamilDevelopments commented
We can do it later.

2023-04-09 11:04 UTC, Vertonowsky approved these changes, later dismissed

2023-04-09 12:21 UTC, KamilDevelopments approved these changes

2023-04-09 12:48 UTC, kestivvi commented
> Game does't recognise someone leaving the room. I created room on one device, closed an app and than opened it again and couldn't do anything becouse game still tought im in waiting room. We need to implement removing player from the room when he presses go back button or just closes an app.

Now, I actually implemented it partially. When some user loses theirs connection, others are notified with `LEAVE_ROOM_RESPONSE` and user that lost connection is removed from the room as well as from the entire database.

Lost connection occur, when you close the app and close it from the drawer (minimized apps), so only minimizing does nothing. There for sure some events in the app tha we can use, but it's android stuff that I don't know much.

2023-04-09 15:27 UTC, Vertonowsky approved these changes

2023-04-09 17:03 UTC, merged