Change language
Splendor-Mobile-Game/ClientSide pull request #57
Opened 2023-04-14 10:37 UTC by KamilDevelopments

Added polish translation + Option to switch between languages.

Also there are some strings doubled, that we should delete later.

2023-04-14 10:45 UTC, EaZZyHK approved these changes, later dismissed

2023-04-14 11:20 UTC, kestivvi requested changes
Consider scenario:
1. I run the app, default is english
2. I click on the UK's flag
3. It should do nothing, but it reloads the activity.

Can we check for it? And only reload the activity if the language user clicks is not set?

2023-04-14 14:32 UTC, KamilDevelopments commented
I fixed the issues, but there is still a problem, it takes like 3 secounds for android to initialize some localizations, and before theyre loaded you will still be able to refresh the activity. If we really want to resolver this issue, we should move language options to settings or block the buttons for few secounds at the start. I dont think its a big deal for now tho.

2023-04-14 17:05 UTC, kestivvi submitted a review, later dismissed

2023-04-16 16:51 UTC, EaZZyHK approved these changes

2023-04-16 20:48 UTC, kestivvi approved these changes

2023-04-16 21:07 UTC, merged